/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const lo_cloneDeep: typeof import('lodash-es').cloneDeep
  const lo_debounce: typeof import('lodash-es').debounce
  const lo_get: typeof import('lodash-es').get
  const lo_groupBy: typeof import('lodash-es').groupBy
  const lo_isUndefined: typeof import('lodash-es').isUndefined
  const lo_omit: typeof import('lodash-es').omit
  const lo_omitBy: typeof import('lodash-es').omitBy
  const lo_pick: typeof import('lodash-es').pick
  const lo_random: typeof import('lodash-es').random
  const lo_set: typeof import('lodash-es').set
  const lo_throttle: typeof import('lodash-es').throttle
}
